name: Ensure code quality

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dart
        uses: subosito/flutter-action@v2.8.0

      - name: Install dependencies
        shell: bash
        run: |
          flutter pub get
          flutter pub global activate pana
          
      - name: Verify formatting
        run: flutter format --set-exit-if-changed .

      - name: Analyze source code
        run: flutter analyze --fatal-infos --fatal-warnings

      - name: Verify Pub Score
        run: bin/ensure_pana_score.sh
        
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install flutter
        uses: subosito/flutter-action@v2.8.0

      - name: Install dependencies
        run: |
          flutter pub get
          flutter pub global activate coverage

      - name: Run tests
        run: flutter test
        
